// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYP7eQTrlovacLlypzkAOX03kLNXAZ1vk',
    appId: '1:668625820668:web:ae36c8cea3c9befcba7079',
    messagingSenderId: '668625820668',
    projectId: 'all4u-d7374',
    authDomain: 'all4u-d7374.firebaseapp.com',
    storageBucket: 'all4u-d7374.appspot.com',
    measurementId: 'G-5GRW6YFE4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABYiPpJRt6xOFiuszxbwkGuixf_B1uzCE',
    appId: '1:668625820668:android:9d41716542996602ba7079',
    messagingSenderId: '668625820668',
    projectId: 'all4u-d7374',
    storageBucket: 'all4u-d7374.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDTlkzhWrA-scHQR6KFPoy4uHaEIl0XBQ',
    appId: '1:668625820668:ios:183270ba774f0dd2ba7079',
    messagingSenderId: '668625820668',
    projectId: 'all4u-d7374',
    storageBucket: 'all4u-d7374.appspot.com',
    iosClientId: '668625820668-t60ib86ft2vbumrnpngr8uo6sn3po4cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDTlkzhWrA-scHQR6KFPoy4uHaEIl0XBQ',
    appId: '1:668625820668:ios:183270ba774f0dd2ba7079',
    messagingSenderId: '668625820668',
    projectId: 'all4u-d7374',
    storageBucket: 'all4u-d7374.appspot.com',
    iosClientId: '668625820668-t60ib86ft2vbumrnpngr8uo6sn3po4cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );
}
